export const AUTHENTICATING_USER = 'AUTHENTICATING_USER'
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'
export const AUTHENTICATION_ABORTED = 'AUTHENTICATION_ABORTED'

export const FETCHING_INITIAL_POSTS = 'FETCHING_INITIAL_POSTS'
export const INITIAL_POSTS_SUCCESS = 'INITIAL_POSTS_SUCCESS'
export const INITIAL_POSTS_FAILURE = 'INITIAL_POSTS_FAILURE'
export const INITIAL_POSTS_ABORTED = 'INITIAL_POSTS_ABORTED'

export const FETCHING_RECENT_POSTS = 'FETCHING_RECENT_POSTS'
export const RECENT_POSTS_SUCCESS = 'RECENT_POSTS_SUCCESS'
export const RECENT_POSTS_FAILURE = 'RECENT_POSTS_FAILURE'
export const RECENT_POSTS_ABORTED = 'RECENT_POSTS_ABORTED'

export const FETCHING_FOCUSED_POST = 'FETCHING_FOCUSED_POST'
export const FOCUSED_POST_SUCCESS = 'FOCUSED_POST_SUCCESS'
export const FOCUSED_POST_FAILURE = 'FOCUSED_POST_FAILURE'
export const FOCUSED_POST_ABORTED = 'FOCUSED_POST_ABORTED'

export const FETCHING_SEARCH_RESULT = 'FETCHING_SEARCH_RESULT'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'
export const SEARCH_ABORTED = 'SEARCH_ABORTED'

export const FETCHING_NOTIFICATIONS = 'FETCHING_NOTIFICATIONS'
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS'
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE'
export const NOTIFICATIONS_ABORTED = 'NOTIFICATIONS_ABORTED'

export const FETCHING_PROFILE_DATA = 'FETCHING_PROFILE_DATA'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'
export const PROFILE_ABORTED = 'PROFILE_ABORTED'
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA'

export const PROCESSING_LIKE = 'PROCESSING_LIKE'
export const LIKE_SUCCESS = 'LIKE_SUCCESS'
export const LIKE_FAILURE = 'LIKE_FAILURE'
export const LIKE_ABORTED = 'LIKE_ABORTED'


export const PROCESSING_FOLLOW = 'PROCESSING_FOLLOW'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE'
export const FOLLOW_ABORTED = 'FOLLOW_ABORTED'

export const ADDING_COMMENT = 'ADDING_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'
export const ADD_COMMENT_ABORTED = 'ADD_COMMENT_ABORTED'
export const CLEAR_FOCUSED_POST = 'CLEAR_FOCUSED_POST'

export const POSTING_CONTENT = 'POSTING_CONTENT'
export const POSTING_SUCCESS = 'POSTING_SUCCESS'
export const POSTING_FAILURE = 'POSTING_FAILURE'
export const POSTING_ABORTED = 'POSTING_ABORTED'


export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const HIDE_TAB_BAR = 'HIDE_TAB_BAR';
export const SHOW_TAB_BAR = 'SHOW_TAB_BAR';

